// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: greet_dotnet.proto

package dotnet_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_greet_dotnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_dotnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_dotnet_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// The response message containing the greetings.
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_greet_dotnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greet_dotnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greet_dotnet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_greet_dotnet_proto protoreflect.FileDescriptor

const file_greet_dotnet_proto_rawDesc = "" +
	"\n" +
	"\x12greet_dotnet.proto\x12\x0edotnet_service\x1a\x1cgoogle/api/annotations.proto\" \n" +
	"\fHelloRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1e\n" +
	"\n" +
	"HelloReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2l\n" +
	"\aGreeter\x12a\n" +
	"\bSayHello\x12\x1c.dotnet_service.HelloRequest\x1a\x1a.dotnet_service.HelloReply\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/greet-dotnet/helloB\x1fZ\x1dgo-service/rpc/dotnet-serviceb\x06proto3"

var (
	file_greet_dotnet_proto_rawDescOnce sync.Once
	file_greet_dotnet_proto_rawDescData []byte
)

func file_greet_dotnet_proto_rawDescGZIP() []byte {
	file_greet_dotnet_proto_rawDescOnce.Do(func() {
		file_greet_dotnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_dotnet_proto_rawDesc), len(file_greet_dotnet_proto_rawDesc)))
	})
	return file_greet_dotnet_proto_rawDescData
}

var file_greet_dotnet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greet_dotnet_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: dotnet_service.HelloRequest
	(*HelloReply)(nil),   // 1: dotnet_service.HelloReply
}
var file_greet_dotnet_proto_depIdxs = []int32{
	0, // 0: dotnet_service.Greeter.SayHello:input_type -> dotnet_service.HelloRequest
	1, // 1: dotnet_service.Greeter.SayHello:output_type -> dotnet_service.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greet_dotnet_proto_init() }
func file_greet_dotnet_proto_init() {
	if File_greet_dotnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_dotnet_proto_rawDesc), len(file_greet_dotnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_dotnet_proto_goTypes,
		DependencyIndexes: file_greet_dotnet_proto_depIdxs,
		MessageInfos:      file_greet_dotnet_proto_msgTypes,
	}.Build()
	File_greet_dotnet_proto = out.File
	file_greet_dotnet_proto_goTypes = nil
	file_greet_dotnet_proto_depIdxs = nil
}
