// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package contracts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	HouseNum             string   `protobuf:"bytes,1,opt,name=house_num,json=houseNum,proto3" json:"house_num,omitempty"`
	Building             string   `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Street               string   `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	Locality             string   `protobuf:"bytes,4,opt,name=locality,proto3" json:"locality,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode           string   `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetHouseNum() string {
	if m != nil {
		return m.HouseNum
	}
	return ""
}

func (m *Address) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

type Person struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32               `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Addresses            map[string]*Address `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetAddresses() map[string]*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "sample.msglib.Address")
	proto.RegisterType((*Person)(nil), "sample.msglib.Person")
	proto.RegisterMapType((map[string]*Address)(nil), "sample.msglib.Person.AddressesEntry")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xb1, 0x6a, 0xe3, 0x40,
	0x10, 0x45, 0x96, 0x2d, 0x5b, 0xa3, 0x3b, 0xdf, 0xb1, 0x70, 0x46, 0xe8, 0x0e, 0xce, 0x88, 0x2b,
	0x5c, 0x1c, 0x12, 0xf8, 0x9a, 0x23, 0x9d, 0x6d, 0x82, 0x9b, 0x10, 0x82, 0x48, 0x95, 0xc6, 0xac,
	0xa5, 0x41, 0x11, 0x5e, 0xed, 0x0a, 0xed, 0x2a, 0xe0, 0x36, 0xbf, 0x90, 0x3f, 0x48, 0x9b, 0x1f,
	0x49, 0x9f, 0x5f, 0xc8, 0x87, 0x04, 0xed, 0xca, 0x04, 0x07, 0x57, 0xe9, 0xde, 0xbc, 0x37, 0x6f,
	0xde, 0xcc, 0xb2, 0xf0, 0xa5, 0xc2, 0x5a, 0x0a, 0x1e, 0x55, 0xb5, 0x50, 0x82, 0x7c, 0x95, 0xb4,
	0xac, 0x18, 0x46, 0xa5, 0xcc, 0x59, 0xb1, 0x0d, 0x7e, 0xe5, 0x42, 0xe4, 0x0c, 0x63, 0x5a, 0x15,
	0x31, 0xe5, 0x5c, 0x28, 0xaa, 0x0a, 0xc1, 0xa5, 0x69, 0x0e, 0x9f, 0x2c, 0x18, 0x2e, 0xb2, 0xac,
	0x46, 0x29, 0xc9, 0x4f, 0x70, 0x6f, 0x45, 0x23, 0x71, 0xc3, 0x9b, 0xd2, 0xb7, 0xa6, 0xd6, 0xcc,
	0x4d, 0x46, 0x9a, 0xb8, 0x6c, 0x4a, 0x12, 0xc0, 0x68, 0xdb, 0x14, 0x2c, 0x2b, 0x78, 0xee, 0xf7,
	0x8c, 0x76, 0xa8, 0xc9, 0x04, 0x1c, 0xa9, 0x6a, 0x44, 0xe5, 0xdb, 0x5a, 0xe9, 0xaa, 0xd6, 0xc3,
	0x44, 0x4a, 0x59, 0xa1, 0xf6, 0x7e, 0xdf, 0x78, 0x0e, 0x35, 0x21, 0xd0, 0x4f, 0x5b, 0x7e, 0xa0,
	0x79, 0x8d, 0xc9, 0x6f, 0xf0, 0x2a, 0x21, 0x15, 0x65, 0x9b, 0x54, 0x64, 0xe8, 0x3b, 0x5a, 0x02,
	0x43, 0xad, 0x44, 0x86, 0xe1, 0xb3, 0x05, 0xce, 0x95, 0xbe, 0xb5, 0xf5, 0x73, 0x5a, 0x62, 0xb7,
	0xa7, 0xc6, 0xe4, 0x3b, 0xd8, 0x34, 0x47, 0xbd, 0xde, 0x20, 0x69, 0x21, 0x59, 0x82, 0x4b, 0xcd,
	0x75, 0x28, 0x7d, 0x7b, 0x6a, 0xcf, 0xbc, 0xf9, 0x9f, 0xe8, 0xe8, 0x7d, 0x22, 0x33, 0x2f, 0x5a,
	0x1c, 0xda, 0xce, 0xb9, 0xaa, 0xf7, 0xc9, 0xbb, 0x2d, 0xb8, 0x86, 0xf1, 0xb1, 0xd8, 0xe6, 0xec,
	0x70, 0xdf, 0x45, 0xb7, 0x90, 0xfc, 0x85, 0xc1, 0x1d, 0x65, 0x8d, 0xc9, 0xf6, 0xe6, 0x93, 0x0f,
	0x19, 0x9d, 0x3f, 0x31, 0x4d, 0x67, 0xbd, 0xff, 0xd6, 0xfc, 0xd1, 0x82, 0xb1, 0x89, 0x4e, 0x30,
	0x2f, 0x64, 0x3b, 0x76, 0x0d, 0xce, 0x85, 0x10, 0xbb, 0xa6, 0x22, 0x3f, 0x4e, 0xee, 0x18, 0x9c,
	0xa6, 0xc3, 0x6f, 0xf7, 0x2f, 0xaf, 0x0f, 0x3d, 0x97, 0x0c, 0x63, 0x66, 0xec, 0x6b, 0x70, 0x56,
	0x35, 0x52, 0x85, 0x9f, 0x1b, 0x14, 0x0e, 0xe3, 0x54, 0xdb, 0x97, 0xde, 0x8d, 0x9b, 0x0a, 0xae,
	0x6a, 0x9a, 0x2a, 0xb9, 0x75, 0xf4, 0x8f, 0xf9, 0xf7, 0x16, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xf1,
	0x96, 0xca, 0x6e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonRegistryClient is the client API for PersonRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonRegistryClient interface {
	Lookup(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	Create(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
}

type personRegistryClient struct {
	cc *grpc.ClientConn
}

func NewPersonRegistryClient(cc *grpc.ClientConn) PersonRegistryClient {
	return &personRegistryClient{cc}
}

func (c *personRegistryClient) Lookup(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/sample.msglib.PersonRegistry/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personRegistryClient) Create(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/sample.msglib.PersonRegistry/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonRegistryServer is the server API for PersonRegistry service.
type PersonRegistryServer interface {
	Lookup(context.Context, *Person) (*Person, error)
	Create(context.Context, *Person) (*Person, error)
}

// UnimplementedPersonRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedPersonRegistryServer struct {
}

func (*UnimplementedPersonRegistryServer) Lookup(ctx context.Context, req *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (*UnimplementedPersonRegistryServer) Create(ctx context.Context, req *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterPersonRegistryServer(s *grpc.Server, srv PersonRegistryServer) {
	s.RegisterService(&_PersonRegistry_serviceDesc, srv)
}

func _PersonRegistry_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonRegistryServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.msglib.PersonRegistry/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonRegistryServer).Lookup(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.msglib.PersonRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonRegistryServer).Create(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample.msglib.PersonRegistry",
	HandlerType: (*PersonRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _PersonRegistry_Lookup_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PersonRegistry_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
