// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: greet_go.proto

package go_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_greet_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_go_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_greet_go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greet_go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greet_go_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LiveDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveDataRequest) Reset() {
	*x = LiveDataRequest{}
	mi := &file_greet_go_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveDataRequest) ProtoMessage() {}

func (x *LiveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_go_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveDataRequest.ProtoReflect.Descriptor instead.
func (*LiveDataRequest) Descriptor() ([]byte, []int) {
	return file_greet_go_proto_rawDescGZIP(), []int{2}
}

type LiveDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveDataReply) Reset() {
	*x = LiveDataReply{}
	mi := &file_greet_go_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveDataReply) ProtoMessage() {}

func (x *LiveDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_greet_go_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveDataReply.ProtoReflect.Descriptor instead.
func (*LiveDataReply) Descriptor() ([]byte, []int) {
	return file_greet_go_proto_rawDescGZIP(), []int{3}
}

func (x *LiveDataReply) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_greet_go_proto protoreflect.FileDescriptor

const file_greet_go_proto_rawDesc = "" +
	"\n" +
	"\x0egreet_go.proto\x12\n" +
	"go_service\x1a\x1cgoogle/api/annotations.proto\" \n" +
	"\fHelloRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1e\n" +
	"\n" +
	"HelloReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x11\n" +
	"\x0fLiveDataRequest\"#\n" +
	"\rLiveDataReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data2\xab\x01\n" +
	"\aGreeter\x12U\n" +
	"\bSayHello\x12\x18.go_service.HelloRequest\x1a\x16.go_service.HelloReply\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0f/greet-go/hello\x12I\n" +
	"\vGetLiveData\x12\x1b.go_service.LiveDataRequest\x1a\x19.go_service.LiveDataReply\"\x000\x01B\x1bZ\x19go-service/rpc/go-serviceb\x06proto3"

var (
	file_greet_go_proto_rawDescOnce sync.Once
	file_greet_go_proto_rawDescData []byte
)

func file_greet_go_proto_rawDescGZIP() []byte {
	file_greet_go_proto_rawDescOnce.Do(func() {
		file_greet_go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_go_proto_rawDesc), len(file_greet_go_proto_rawDesc)))
	})
	return file_greet_go_proto_rawDescData
}

var file_greet_go_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_greet_go_proto_goTypes = []any{
	(*HelloRequest)(nil),    // 0: go_service.HelloRequest
	(*HelloReply)(nil),      // 1: go_service.HelloReply
	(*LiveDataRequest)(nil), // 2: go_service.LiveDataRequest
	(*LiveDataReply)(nil),   // 3: go_service.LiveDataReply
}
var file_greet_go_proto_depIdxs = []int32{
	0, // 0: go_service.Greeter.SayHello:input_type -> go_service.HelloRequest
	2, // 1: go_service.Greeter.GetLiveData:input_type -> go_service.LiveDataRequest
	1, // 2: go_service.Greeter.SayHello:output_type -> go_service.HelloReply
	3, // 3: go_service.Greeter.GetLiveData:output_type -> go_service.LiveDataReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greet_go_proto_init() }
func file_greet_go_proto_init() {
	if File_greet_go_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_go_proto_rawDesc), len(file_greet_go_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_go_proto_goTypes,
		DependencyIndexes: file_greet_go_proto_depIdxs,
		MessageInfos:      file_greet_go_proto_msgTypes,
	}.Build()
	File_greet_go_proto = out.File
	file_greet_go_proto_goTypes = nil
	file_greet_go_proto_depIdxs = nil
}
