apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          # volumes:
          #   - name: proto-descriptor
          #     volumeSource:
          #       configMap:
          #         localObjectReference:
          #           name: proto-descriptor
          #         items:
          #           - key: desc.pb
          #             path: desc.pb
          # volumeMounts:
          #   - name: proto-descriptor
          #     readOnly: true
          #     mountPath: "/etc/envoy"
