apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway # The actual name of the ingress gateway deployment
              patches:
                - path: spec.template.spec.volumes[-1] # Append to the existing list of volumes
                  value:
                    name: proto-descriptor-vol
                    configMap:
                      name: proto-descriptor
                      items:
                        - key: desc.pb
                          path: desc.pb
                # Assuming the primary Envoy container is at index 0
                - path: spec.template.spec.containers[0].volumeMounts[-1] # Append to the existing list of volume mounts
                  value:
                    name: proto-descriptor-vol
                    readOnly: true
                    mountPath: "/etc/envoy"
