apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
  namespace: istio-system
spec:
  selfSigned: {}

# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
#   namespace: istio-system
# spec:
#   acme:
#     # Let's Encrypt uses this to contact you about expiring
#     # certificates, and issues related to your account.
#     email: sangzhuoyangy@gmail.com
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     solvers:
#     - http01:
#         ingress:
#           class: istio

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-certs
  namespace: istio-system
spec:
  secretName: ingressgateway-certs
  commonName: "localhost"
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
  dnsNames:
  - "localhost"
