apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-dev
  namespace: istio-system
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-certs
  namespace: istio-system
spec:
  secretName: ingressgateway-certs
  commonName: "127.0.0.1"
  issuerRef:
    name: local-dev
    kind: ClusterIssuer
  dnsNames:
  - "127.0.0.1"
